// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface UpdateCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.CompteRequest compte = 2;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.CompteRequest compte = 2;</code>
   * @return The compte.
   */
  ma.projet.grpc.stubs.CompteRequest getCompte();
  /**
   * <code>.CompteRequest compte = 2;</code>
   */
  ma.projet.grpc.stubs.CompteRequestOrBuilder getCompteOrBuilder();
}
